version: "3.1"

services:
    front:
        build:
            context: ./auth/front
            dockerfile: Dockerfile.dev
        user: root
        restart: always
        depends_on:
            - auth_back
        volumes:
            - ./front:/app
            - ./nginx/dev:/app/.cert
            - /app/node_modules
        stdin_open: true
        tty: true

    back:
        build:
            context: ./back
            dockerfile: Dockerfile.dev
        restart: always
        depends_on:
            - db
        volumes:
            - ./back/:/app/
            - ./nginx/dev:/app/.cert
            - /app/node_modules
        environment:
            - POSTGRES_HOST=auth_db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=$POSTGRES_AUTH_PASSWORD
            - POSTGRES_DATABASE=$POSTGRES_AUTH_DATABASE
            - JWT_ACCESS_EXPIRES=$JWT_ACCESS_EXPIRES
            - JWT_REFRESH_EXPIRES=$JWT_REFRESH_EXPIRES

    auth_db:
        image: postgres:14
        restart: always
        environment:
            - POSTGRES_PASSWORD=$POSTGRES_AUTH_PASSWORD
        volumes:
            - ./auth/db:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always

    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/dev:/etc/nginx/cert
